### ISSUE TITLE
Q/A: how to disable idea snnipets.

### ISSUE THREAD

**Issue by dhun** [atom/language-todo#58]
A generic entity class has an ID field defined.
When the idea snippet is defined, the following will be listed whe enter `entity.i`.

* idea
* ID

Is there any way to disable the idea snippet?
Or whether you can set whether to use the idea snippet or not?

I am using `language-todo` while commenting out `idea` part of language-todo/snippets/todo.cson.

I think that it is not much to use the idea snippet compared to the ID field.
I think that there are many people in trouble for the same reason.
I am really happy to provide it as a package feature. plz

**Comment by piuccio** [comment]
I hate the snippet `question`, would be nice to have a way to configure which snippets are active

**Comment by Stanko** [comment]
Same here.
`QUESTION` is really annoying.

Plus in CSS files when I start typing word `color` (`font-co`, `border-co`...) autocomplete offers `COMBAK` as first option.

**Comment by mrleblanc101** [comment]
Snippets suggestions should only be enabled in comments as TODO/FIX statement are only used in comments. Furthermore the syntax highlighting is only for comments so it would only make sense and would fix this problem. Writing CSS in comments is very rare so still having these suggestions wouldn't really be a problem.

**Comment by axe-z** [comment]
There should be a compiled snippet file, where you see every snippet , your own, and the added ones, and be able to clean up stuff . AND a grammar default selection for extension ..

**Comment by Ben3eeE** [comment]
Atom 1.33 (currently in beta) has the ability to disable all snippets from the any language package that includes snippets like `language-todo` package in the packages settings. If you want to add some of them back there is a copy button so you can paste it to your personal snippets file.

![image](https://user-images.githubusercontent.com/1058982/48588169-3dd9f480-e936-11e8-93cc-beda9d74dd2f.png)

---

Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by axe-z** [comment]
wow I did add the line for the empty body, atom is not restarting.. no safe mode. I see atom in the upper corner with only quit in the menu

**Comment by axe-z** [comment]
![capture d ecran le 2018-11-15 a 18 41 30](https://user-images.githubusercontent.com/27289270/48588678-12d7ac80-e906-11e8-9091-8b461fb5e14b.png)
any idea ? is there a way out ... except vscode... installed it again. removed files from librairy... tried atom --safe ... nothing
