### ISSUE TITLE
How do releases happen?

### ISSUE THREAD

**Issue by bhhaskin** [atom/language-todo#69]
Do releases happen automatically with a version number bump? Or are they a manual process? What constitutes a release?

Just checking if there is anything else I need to do with regards to my PR #68

**Comment by Ben3eeE** [comment]
A new version of language-todo will be released manually by one of the maintainers. After that it will be added to the package.json of the atom/atom repository to include it in an upcoming version of Atom (Usually that would be the next beta).

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by bhhaskin** [comment]
Thanks! exactly what I was looking for!

**Comment by 50Wliu** [comment]
Yep.  Since Atom core packages are tied to Atom versions, they can't be auto-updated and so I generally wait a while so that I can do releases for multiple packages at the same time.  Your PR will most likely be included in Atom 1.23.
