### ISSUE TITLE
Add author to comment

### ISSUE THREAD

**Issue by jimmywarting** [atom/language-todo#76]
In a project with teams it would be nice to see who wrote the comment so i think it would be nice if the snippet would generate something like this:
```js
// TODO: (<name>) validate username 
```

where name is taken from `git config user.name` and fallback to the name of the account in the OS

**Comment by 50Wliu** [comment]
Thanks for the submission!

That would definitely be useful in some people's workflows. However, it is not something that is within the scope that we have have envisioned for this package. For that reason, and because we wouldn't be able to populate the name value with anything but a placeholder value, I'm going to close this. It sounds like a great idea for an Atom package though. If you need help building this as a package, please check out the [Atom Flight Manual section on publishing your own packages](https://flight-manual.atom.io) and feel free to ask any questions you have on [Discuss, the official Atom and Electron message board](https://discuss.atom.io) or the Atom Slack team.

Thanks again for contributing to Atom :+1:
