### ISSUE TITLE
Simply Doesn't Work

### ISSUE THREAD

**Issue by haximilian** [atom/language-todo#86]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom is not highlighting "TODO" statements at all.

### Steps to Reproduce

1. Open Atom
2. Open or create any file (tested with ".js" and ".c")
3. Type "// TODO: test", "// TODO test", "// todo: test", or "// todo test"

**Expected behavior:**
"TODO" should have been highlighted (last I recall, in a purple color, I think)

**Actual behavior:**
"TODO" looks like just any other word in a comment: gray and boring

**Reproduces how often:**
100% of the time (it used to work, but today I noticed that it had stopped working. Don't actually know how long it's been since it stopped working, but it was working last Sunday).

### Versions
Atom    : 1.32.0
Electron: 2.0.12
Chrome  : 61.0.3163.100
Node    : 8.9.3

### Additional Information
No errors were reported in the Developer Console while I was testing it, except for some warning that started with:
> Electron Security Warning  /usr/lib/electron/re...ity-warnings.js
> Security Policy Set or a policy with "unsafe-eval" enabled. This exposes users of this app to unnecessary security risks

**Comment by Ben3eeE** [comment]
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/language-todo/issues/82. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Comment by chittolina** [comment]
I noticed that using `/* TODO: anything */ works fine.
